### PR TITLE
new hydrostatic data

### PR DESCRIPTION
**Pull request by simone-silvestri**
Generated with computed halos in `compute_vertically_integrated_lateral_areas!`

### CODE REVIEW

**Comment by glwagner** [comment]
This PR also updates the LES regression test data? Is that intended?

**Comment by glwagner** [comment]
Why can't the PR just download the data from a branch? Why do we have to merge the files into `main` here?

**Review by glwagner — APPROVED** [review]

**Comment by simone-silvestri** [comment]
Update...

it works also with branches!

**Comment by glwagner** [comment]
That's really nice for temporary data because we can delete the branch in the future and save space I think.

**Comment by glwagner** [comment]
shall we close?

**Pull request closed without merging**
